import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "csshelper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav className="w-full flex">
          <h1>Title</h1>
          <div>
            <h1>Link 1</h1>
            <h1>Link 2</h1>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
